### ISSUE TITLE
Want a PDF version

### ISSUE THREAD

**Issue by lebarde** [sequelize/doc#160]
Hello,
As I often develop in the train I have not access to Sequelize documentation. I know I can download the doc project, but it could be good if we could directly download a PDF (or epub) version of the doc.

Thanks by advance !

**Comment by randdusing** [comment]
Are PDFs available now? I googled site:sequelize.readthedocs.org pdf, but found nothing.

**Comment by sdepold** [comment]
Hm not sure. It does not seem so.
