### ISSUE TITLE
Specifying associations via migrations

### ISSUE THREAD

**Issue by jonlambert** [sequelize/doc#176]
When defining a migration, how can I specify a relationship to another Model (thus creating the valid foreign keys)?

There's plenty of documentation for adding this via .sync(), but none that I can find for adding via migrations.

**Comment by cusspvz** [comment]
Hey @jonlambert ,
I'm using **sequelize** for about 2 years, and in the past I had loaded models on migrations until I had experienced some problems with that. Migrations are intended to automate the job for applying database changes during development, meaning that your models will be always updated. As so, IMHO, you should not use models during migrations and use queries instead.

**Comment by jonlambert** [comment]
Absolutely, agreed. However, what I'm looking to do is add a relationship in the same way as the models do - with foreign keys etc. There is no documentation on how to re-create the database structure generated by the Models API in a migration.

**Comment by cusspvz** [comment]
Which SQL dialect/system are you using?

Anyway, you could debug some piece of your code that uses **sequelize** (trough `logging` option) and replicate it on a migration.
